### PR TITLE
speedy: fix bugs involving watchlist preferences

### LINKED ISSUE #1427: All CSD tagged articles getting added to watchlist, despite selecting "don't add to watchlist"
Pretty much the title. Here's a screenshot of my settings.

image

### PR DESCRIPTION
**Pull request by NovemLinguae**
Fixes #1427 All CSD tagged articles getting added to watchlist, despite selecting "don't add to watchlist"

Also fixes a bug where all CSD watchlisting was permanent, instead of taking into account the duration set in the user's preferences.

### CODE REVIEW

**Review by siddharthvp — CHANGES_REQUESTED** [review]
`let` is ES6, so can't be used here. Please use `var` instead and make sure that `npm run lint:fix` is passing.

File: modules/twinklespeedy.js [hunk 1]
```diff
@@ -2027,9 +2027,19 @@ Twinkle.speedy.callback.evaluateUser = function twinklespeedyCallbackEvaluateUse
 	});
 
 	// analyse each criterion to determine whether to watch the page/notify the creator
-	var watchPage = normalizeds.some(function(norm) {
-		return Twinkle.getPref('watchSpeedyPages').indexOf(norm) !== -1 && Twinkle.getPref('watchSpeedyExpiry');
+	// analyse each criterion to determine whether to watch the page/notify the creator
```
Comment (siddharthvp) [inline modules/twinklespeedy.js:2030]:
```suggestion
```
this comment has been duplicated

**Comment by NovemLinguae** [comment]
This one is ready for re-review :)

File: modules/twinklespeedy.js [hunk 2]
```diff
@@ -2027,9 +2027,18 @@ Twinkle.speedy.callback.evaluateUser = function twinklespeedyCallbackEvaluateUse
...
+		var isWatchingAllCSDs = Twinkle.getPref('watchSpeedyExpiry') !== 'no';
+		var shouldWatchThis = isWatchingThisCriteria && isWatchingAllCSDs;
+		return shouldWatchThis;
 	});
+
+	// if we should watch the page, replace "true" with the duration we should watch for
+	if (watchPage) {
+		watchPage = Twinkle.getPref('watchSpeedyExpiry');
+	}
+
```
Comment (siddharthvp) [inline modules/twinklespeedy.js:2041]: I think this is equivalent to just 
```js
	var watchPage = normalizeds.some(function(csdCriteria) {
		return Twinkle.getPref('watchSpeedyPages').indexOf(csdCriteria) !== -1;
	}) && Twinkle.getPref('watchSpeedyExpiry');
```
?
Twinkle.getPref('watchSpeedyExpiry') doesn't need to be checked every time in the loop, and if normalizeds.some returns true, watchSpeedyExpiry being `'no'` gives the desired effect

**Comment by siddharthvp** [comment]
From the issue, I can't reproduce the "unchecking all the boxes still [adds pages to watchlist]" bug. Also don't how this patch would fix that issue assuming it's there.
