### PR TITLE
warn & block: Change reference to "level 2 heading" to "talk page section"

### LINKED ISSUE #1292: Modal says "level 2 warning" when placing level 1 warning
Steps to reproduce:

- Go to an uncreated talk page.
- Place a level 1 vandalism warning.
- Modal pops up that says something like "No level 2 warning detected for this month, creating heading"

The level 2 part should correspond to the actual level of the warning.

### PR DESCRIPTION
**Pull request by molly**
Reduces potential confusion between "level 2 heading" and "level 2 warning" in the informational messages. Closes #1292.

### CODE REVIEW

File: modules/twinkleblock.js [hunk 1]
```diff
@@ -1914,7 +1914,7 @@ Twinkle.block.callback.main = function twinkleblockcallbackMain(pageobj) {
 	params.indefinite = Morebits.string.isInfinity(params.expiry);
 
 	if (Twinkle.getPref('blankTalkpageOnIndefBlock') && params.template !== 'uw-lblock' && params.indefinite) {
-		Morebits.status.info('Info', 'Blanking talk page per preferences and creating a new level 2 heading for the date');
+		Morebits.status.info('Info', 'Blanking talk page per preferences and creating a new talk page section for this month');
```
Comment (Amorymeltzer) [inline modules/twinkleblock.js:1917]: @molly I didn't even think about this one!  There's another in line [https://github.com/wikimedia-gadgets/twinkle/pull/1294/files#diff-eddb511f8eaac257a180d1631b66386089bd898ed7b3725c0577f9732882700cR1936 1936], wanna grab that?

Comment (molly) [reply modules/twinkleblock.js:1917]: Oh, good catch! I've made the change (and squashed the commits again).

**Review by Amorymeltzer — APPROVED** [review]
LGTM!
