### PR TITLE
tag: fix pagetriagelist API undefined error

### LINKED ISSUE #1737: friendlytag: response.pagetriagelist.pages[0] is undefined
Steps:
- Open https://en.wikipedia.org/wiki/Cambuquira
- Select "Tag"

Line: [friendlytag.js:56](https://github.com/wikimedia-gadgets/twinkle/blob/0654f8c1beefaefd807e6a045fdd3315c854afdb/modules/friendlytag.js#L56)

XHR response:
```json
{
    "pagetriagelist": {
        "result": "warning",
        "pages_missing_metadata": [
            8657842
        ],
        "pages": []
    }
}
```

### PR DESCRIPTION
**Pull request by NovemLinguae**
Fix #1737

### CODE REVIEW

File: modules/friendlytag.js [hunk 1]
```diff
@@ -53,7 +53,16 @@ Twinkle.tag.callback = function friendlytagCallback() {
...
-		var isMarkedAsReviewed = response.pagetriagelist.pages[0].patrol_status > 0;
+		var isMarkedAsReviewed;
+
+		// Handle edge case where pagetriagelist API returns "pages_missing_metadata"
+		var valid_response = response.pagetriagelist.pages[0] !== undefined;
+		if (valid_response) {
+			isMarkedAsReviewed = response.pagetriagelist.pages[0].patrol_status > 0;
+		} else {
+			isMarkedAsReviewed = true;
+		}
```
Comment (siddharthvp) [inline modules/friendlytag.js:64]: Can be written more concisely:
```suggestion
		// Handle edge case where pagetriagelist API returns "pages_missing_metadata"
		var isMarkedAsReviewed = response.pagetriagelist.pages[0] ?
			response.pagetriagelist.pages[0].patrol_status > 0 : 
			true;
```
